import './styles.css';
import {getSessions, getSession, saveSession, deleteSession, importSessions} from './store.js';

const $ = selector => document.querySelector(selector);
const worker = new Worker(new URL('./translate.worker.js', import.meta.url), {type:'module'});
const state = {ready:false, session:null, recognition:null, listening:false, paused:false, stopping:false, clock:null, partial:'', pending:null, queue:[], queued:new Set(), history:[], restartTimer:null, restartCount:0, started:false, glossary:[]};
const dateFormat = new Intl.DateTimeFormat('en-MY', {timeZone:'Asia/Kuala_Lumpur', dateStyle:'medium', timeStyle:'short'});
const timeFormat = new Intl.DateTimeFormat('en-MY', {timeZone:'Asia/Kuala_Lumpur', timeStyle:'medium'});
const topics = [[/HF2/i,'HF2 equipment discussion'],[/MicroSD/i,'MicroSD production discussion'],[/模具|mold/i,'Mold discussion'],[/plasma|電漿/i,'Plasma discussion'],[/烘烤|bake|PMC/i,'Baking discussion']];
const builtInTerms = [{zh:'清模',en:'mold cleaning'}, {zh:'模具',en:'mold'}, {zh:'基板',en:'substrate'}, {zh:'電漿',en:'plasma'}, {zh:'柱塞',en:'plunger'}];
const escapeHTML = value => String(value??'').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const duration = seconds => `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
const titleFrom = session => topics.find(([pattern]) => pattern.test(session.segments.map(x=>x.original+' '+x.english).join(' ')))?.[1] || 'Mandarin conversation';
const matchingTerms = original => [...builtInTerms,...state.glossary].filter(term=>original.includes(term.zh));
let toastTimer;
let writes = Promise.resolve();
function toast(message){$('#toast').textContent=message;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),5000)}
function persist(session){const snapshot=structuredClone(session);writes=writes.catch(()=>{}).then(()=>saveSession(snapshot));return writes.catch(e=>{toast('Save failed: '+e.message);throw e})}
function safariNotice(){const webkit=!!window.webkitSpeechRecognition;const standalone=window.navigator.standalone===true || matchMedia('(display-mode: standalone)').matches;const node=$('#compatibility');if(standalone)node.textContent='Home Screen web-app mode may block iPhone speech recognition. Open this page in Safari instead. When adding it to Home Screen, turn off “Open as Web App” if shown.';else if(!webkit && !window.SpeechRecognition)node.textContent='Speech recognition is unavailable here. Open the HTTPS page in iPhone Safari.';else node.textContent='Open in Safari and keep it on screen. On iOS 26, turn off “Open as Web App” when adding a Home Screen shortcut.';return !standalone && !!(webkit||window.SpeechRecognition)}
function render(){
  $('#app').innerHTML=`<div class="app"><header class="top"><div class="brand"><span class="mark">↔</span><div><strong>KYNG Interpreter</strong><small>繁體中文 → English</small></div></div><span class="badge">No paid API · Local translation</span></header><nav class="tabs" aria-label="Sections"><button data-view="listen" class="active">Listen</button><button data-view="history">History</button><button data-view="settings">Settings</button></nav><main>
  <section id="listenView"><span class="eyebrow">LIVE WORKSPACE</span><h1>Follow the conversation.</h1><div class="card"><p id="compatibility" class="notice"></p><div class="model"><span class="model-dot" id="modelDot"></span><div><strong id="modelStatus">Preparing translation model…</strong><p id="modelInfo">The first download may take several minutes. No account or payment is required.</p></div></div><div class="status"><span id="listeningStatus">Ready</span><time id="clock">00:00</time></div><button id="start" class="button-main">◉ &nbsp; Start listening</button><div class="row hidden" id="controls"><button id="pause">Pause</button><button id="end" class="end">End & save</button></div><p class="fine">Keep Safari visible and your phone unlocked. Verify names, numbers and safety instructions with the speaker. Ask permission before transcribing others.</p><details><summary>Microphone unavailable? Enter Chinese text</summary><form id="manualForm" class="manual"><textarea id="manualText" lang="zh-Hant" placeholder="Type or paste Traditional Chinese" rows="2" maxlength="1000"></textarea><button type="submit" class="secondary">Translate & save phrase</button></form></details></div><div class="card transcript"><div class="heading"><h2>Conversation</h2><span id="phraseCount">0 phrases</span></div><div class="partial hidden" id="partial"><small>HEARING NOW · 中文</small><p></p></div><div id="phrases"><div class="empty">Chinese speech and English translation appear here.</div></div></div></section>
  <section id="historyView" class="hidden"><span class="eyebrow">SAVED IN THIS SAFARI PROFILE</span><h1>Session history</h1><input class="history-search" id="search" type="search" placeholder="Search transcripts" aria-label="Search transcripts"><div class="history-list" id="historyList"></div></section><section id="detailView" class="hidden"><button class="back" id="back">← History</button><div id="detail"></div></section>
  <section id="settingsView" class="hidden"><span class="eyebrow">YOUR DATA</span><h1>Settings & backup</h1><div class="card settings"><h2>Free, with clear limits</h2><p>Safari speech recognition may use Apple services and need internet. The translation model runs in Safari after download. No paid API key or app server is used. It is a small machine translation model, so it cannot guarantee context-aware AI interpretation.</p><p>Speech may stop if Safari goes into the background or the iPhone locks. This app cannot promise unattended continuous recording. The first model download can be large and translation can be slow.</p><h2>Back up transcripts</h2><p>Safari can clear local data. The downloaded backup is unencrypted JSON. Keep it private. A Safari bookmark and an installed web app can have separate histories.</p><button id="backup" class="secondary">Download backup</button><button id="restore" class="secondary">Import backup</button><input id="restoreFile" class="hidden" type="file" accept="application/json,.json"><h2>Engineering terms</h2><p>Hints appear beside phrases containing these Chinese terms. Check the English yourself: hints do not change the model output.</p><div id="glossaryList"></div><form id="glossaryForm" class="glossary-form"><input id="glossaryZh" placeholder="Chinese term" aria-label="Chinese term" required maxlength="40"><input id="glossaryEn" placeholder="Preferred English term" aria-label="Preferred English term" required maxlength="80"><button class="secondary" type="submit">Add term</button></form></div></section></main><footer>No payments · No server account · Export a backup regularly</footer></div><div id="toast" class="toast hidden" role="status"></div>`;
  document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>show(button.dataset.view));
  $('#start').onclick=start;$('#pause').onclick=pause;$('#end').onclick=end;$('#back').onclick=()=>show('history');$('#search').oninput=renderHistory;
  $('#historyList').onclick=event=>{const item=event.target.closest('[data-id]');if(item)openDetail(item.dataset.id)};
  $('#backup').onclick=backup;$('#restore').onclick=()=>$('#restoreFile').click();$('#restoreFile').onchange=restore;
  $('#glossaryForm').onsubmit=addTerm;$('#glossaryList').onclick=removeTerm;
  $('#manualForm').onsubmit=async event=>{event.preventDefault();const input=$('#manualText');const value=input.value.trim();if(!value)return;try{if(!state.session){await newSession();state.paused=true;state.session.pausedAt=Date.now();$('#start').classList.add('hidden');$('#controls').classList.remove('hidden');$('#pause').disabled=true;$('#listeningStatus').textContent='Manual entry session';state.clock=setInterval(tick,1000)}await addPhrase(value);input.value='';toast('Chinese phrase saved; translation queued')}catch(e){toast('Could not save phrase: '+e.message)}};
  safariNotice();renderGlossary();
}
function show(view){for(const name of ['listen','history','detail','settings'])$('#'+name+'View').classList.toggle('hidden',name!==view);document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));if(view==='history')loadHistory()}
function modelStatus(title,info,ready=false){$('#modelStatus').textContent=title;$('#modelInfo').textContent=info;$('#modelDot').classList.toggle('ready',ready)}
function phraseHTML(phrase,editable=false){const terms=matchingTerms(phrase.original);return `<article class="pair"><time>${escapeHTML(timeFormat.format(new Date(phrase.at)))}</time><label>中文 · ORIGINAL</label><p class="original" lang="zh-Hant">${escapeHTML(phrase.original)}</p><label>ENGLISH ${phrase.edited?'· EDITED': '· LOCAL MODEL'}</label><p class="english ${phrase.english?'':'warning'}">${escapeHTML(phrase.english||phrase.error||'Translation pending')}</p>${terms.length?`<p class="term-hint">Terminology hint: ${terms.map(t=>escapeHTML(t.zh)+' → '+escapeHTML(t.en)).join(' · ')}</p>`:''}${editable?`<div class="phrase-actions"><button data-action="edit" data-phrase="${escapeHTML(phrase.id)}">Correct English</button><button data-action="retry" data-phrase="${escapeHTML(phrase.id)}">Retry model</button></div>`:''}</article>`}
function renderPhrases(){const phrases=state.session?.segments||[];$('#phraseCount').textContent=`${phrases.length} phrase${phrases.length===1?'':'s'}`;$('#phrases').innerHTML=phrases.length?phrases.map(x=>phraseHTML(x)).join(''):'<div class="empty">Chinese speech and English translation appear here.</div>'}
function tick(){if(!state.session)return;const end=state.paused?state.session.pausedAt:Date.now();$('#clock').textContent=duration(Math.max(0,Math.floor((end-new Date(state.session.startedAt).getTime()-state.session.pausedMs)/1000)))}
async function newSession(){const s={id:crypto.randomUUID(),startedAt:new Date().toISOString(),endedAt:null,title:'New session',segments:[],pausedMs:0,pausedAt:0};await persist(s);state.session=s;renderPhrases();return s}
async function addPhrase(text){text=text.trim();if(!text||!state.session||state.stopping)return;const session=state.session;const phrase={id:crypto.randomUUID(),at:new Date().toISOString(),original:text,english:'',error:'',edited:false};session.segments.push(phrase);session.title=titleFrom(session);await persist(session);if(state.session?.id===session.id)renderPhrases();enqueue(session.id,phrase.id)}
function enqueue(sessionId,phraseId){if(state.queued.has(phraseId)||state.pending?.phraseId===phraseId)return;state.queued.add(phraseId);state.queue.push({sessionId,phraseId});sendNext()}
async function recover(){const rows=await getSessions();for(const s of rows)for(const phrase of s.segments)if(!phrase.english)enqueue(s.id,phrase.id);if(rows.some(s=>!s.endedAt))toast('An unfinished session was saved. Open History to review it.')}
async function sendNext(){if(!state.ready||state.pending||!state.queue.length)return;const item=state.queue.shift();state.queued.delete(item.phraseId);state.pending=item;try{await writes.catch(()=>{});const session=await getSession(item.sessionId);const phrase=session?.segments.find(p=>p.id===item.phraseId);if(!phrase||phrase.edited){state.pending=null;return sendNext()}worker.postMessage({type:'translate',id:item.phraseId,text:phrase.original})}catch(e){state.pending=null;toast('Could not load saved phrase: '+e.message);sendNext()}}
worker.onmessage=async({data})=>{if(data.type==='progress')modelStatus(`Downloading model · ${data.progress}%`,'Keep Safari open for the first download.');if(data.type==='status')modelStatus('Downloading translation model…',data.message);if(data.type==='ready'){state.ready=true;modelStatus('Translator ready','Runs locally in Safari; speech recognition uses Safari.',true);sendNext()}if(data.type==='error'){modelStatus('Translation model unavailable',data.message);toast('Translation model failed. Check connection and reload.')}if(data.type==='result'){const item=state.pending;if(!item||item.phraseId!==data.id)return;try{await writes.catch(()=>{});const s=state.session?.id===item.sessionId?state.session:await getSession(item.sessionId);const phrase=s?.segments.find(p=>p.id===data.id);if(phrase&&!phrase.edited){phrase.english=(data.english||'').trim();phrase.error=data.error||'';await persist(s);if(state.session?.id===s.id)renderPhrases();if($('#detailView')&&!$('#detailView').classList.contains('hidden')&&$('#detail').dataset.id===s.id)openDetail(s.id)}}catch(e){toast('Translation save failed: '+e.message)}finally{state.pending=null;sendNext()}}};
function clearRestart(){clearTimeout(state.restartTimer);state.restartTimer=null}
function stopSpeech(message){clearRestart();state.listening=false;state.paused=true;if(state.session&&!state.session.pausedAt)state.session.pausedAt=Date.now();$('#pause').textContent='Resume';$('#listeningStatus').textContent=message;toast(message);if(state.session)persist(state.session).catch(()=>{})}
function createRecognition(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)throw Error('Speech recognition is unavailable. Open this HTTPS page in iPhone Safari.');const recognition=new Recognition();recognition.lang='zh-TW';recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=1;recognition.onresult=event=>{state.restartCount=0;let interim='';for(let i=event.resultIndex;i<event.results.length;i++){const text=event.results[i][0]?.transcript||'';if(event.results[i].isFinal)addPhrase(text).catch(e=>toast('Could not save speech: '+e.message));else interim+=text}state.partial=interim;$('#partial').classList.toggle('hidden',!interim);$('#partial p').textContent=interim};recognition.onerror=event=>{if(['not-allowed','service-not-allowed','audio-capture','network'].includes(event.error))stopSpeech('Speech stopped ('+event.error+'). Check Safari permission and connection.');else if(!['no-speech','aborted'].includes(event.error))toast('Speech error: '+event.error)};recognition.onend=()=>{if(!state.listening||state.paused||state.stopping)return;if(document.hidden)return stopSpeech('Safari went into background. Tap Resume when visible.');if(++state.restartCount>4)return stopSpeech('Speech stopped repeatedly. Tap Resume to try again.');clearRestart();state.restartTimer=setTimeout(()=>{if(state.listening&&!state.paused&&!document.hidden)try{recognition.start()}catch(e){stopSpeech('Speech could not restart: '+e.message)}},Math.min(1200*state.restartCount,5000))};return recognition}
async function start(){if(state.session)return;if(!safariNotice())return toast('Open this page in iPhone Safari to enable speech.');try{state.recognition=createRecognition();await newSession();state.recognition.start();state.listening=true;state.paused=false;state.restartCount=0;state.started=true;$('#start').classList.add('hidden');$('#controls').classList.remove('hidden');$('#listeningStatus').textContent='Listening to Mandarin';state.clock=setInterval(tick,1000);tick();if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{})}catch(e){if(state.session){const s=state.session;s.endedAt=new Date().toISOString();await persist(s).catch(()=>{});state.session=null}toast(e.message)}}
function pause(){if(!state.session)return;if(!state.paused){state.paused=true;state.session.pausedAt=Date.now();state.listening=false;clearRestart();state.recognition?.stop();$('#pause').textContent='Resume';$('#listeningStatus').textContent='Paused'}else{if(document.hidden)return toast('Return to Safari first.');try{state.recognition??=createRecognition();state.recognition.start();state.session.pausedMs+=Date.now()-state.session.pausedAt;state.session.pausedAt=0;state.paused=false;state.listening=true;state.restartCount=0;$('#pause').textContent='Pause';$('#listeningStatus').textContent='Listening to Mandarin'}catch(e){toast('Could not resume: '+e.message)}}persist(state.session).catch(()=>{})}
async function end(){if(!state.session||state.stopping)return;state.stopping=true;state.listening=false;clearRestart();state.recognition?.stop();clearInterval(state.clock);const s=state.session;if(state.paused&&s.pausedAt)s.pausedMs+=Date.now()-s.pausedAt;s.pausedAt=0;s.endedAt=new Date().toISOString();s.title=titleFrom(s);try{await persist(s)}catch{state.stopping=false;return}state.session=null;state.recognition=null;state.paused=false;state.stopping=false;$('#controls').classList.add('hidden');$('#start').classList.remove('hidden');$('#pause').disabled=false;$('#clock').textContent='00:00';renderPhrases();show('history');toast(s.segments.some(x=>!x.english)?'Session saved. Translation continues while Safari stays open.':'Session saved')}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.listening){state.paused=true;state.listening=false;state.session.pausedAt=Date.now();clearRestart();state.recognition?.stop();$('#pause').textContent='Resume';$('#listeningStatus').textContent='Safari hidden · tap Resume';persist(state.session).catch(()=>{})}});
async function loadHistory(){try{state.history=await getSessions();renderHistory()}catch(e){toast('Could not load history: '+e.message)}}
function renderHistory(){const query=$('#search').value.toLowerCase();const rows=state.history.filter(s=>[s.title,...s.segments.flatMap(x=>[x.original,x.english])].join(' ').toLowerCase().includes(query));$('#historyList').innerHTML=rows.length?rows.map(s=>`<button class="history-item" data-id="${escapeHTML(s.id)}"><small>${escapeHTML(dateFormat.format(new Date(s.startedAt)))} · ${s.segments.length} phrases${!s.endedAt?' · Unfinished':''}</small><strong>${escapeHTML(s.title)}</strong><p>${escapeHTML(s.segments.find(x=>x.english)?.english||'Tap to view transcript')}</p></button>`).join(''):'<div class="card empty">No sessions found.</div>'}
async function openDetail(id){const s=await getSession(id);if(!s)return toast('Session not found');$('#detail').dataset.id=id;$('#detail').innerHTML=`<div class="card detail"><span class="eyebrow">SESSION TRANSCRIPT</span><h2>${escapeHTML(s.title)}</h2><p class="meta">${escapeHTML(dateFormat.format(new Date(s.startedAt)))} · ${s.segments.length} phrases${s.endedAt?'':' · Unfinished'}</p><div class="detail-controls"><button id="rename">Rename</button><button id="copy">Copy</button><button id="remove" class="danger">Delete</button></div><p>Keyword title and machine translations need review. Correct individual English phrases below.</p>${s.segments.map(x=>phraseHTML(x,true)).join('')||'<p>No speech captured.</p>'}</div>`;show('detail');$('#rename').onclick=async()=>{const title=prompt('Session title',s.title)?.trim();if(!title)return;s.title=title.slice(0,100);await persist(s);openDetail(id)};$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(`${s.title}\n${dateFormat.format(new Date(s.startedAt))}\n\n${s.segments.map(x=>`${timeFormat.format(new Date(x.at))}\n中文: ${x.original}\nEnglish: ${x.english||''}`).join('\n\n')}`);toast('Transcript copied')}catch{toast('Copy failed; download a backup instead')}};$('#remove').onclick=async()=>{if(!confirm('Delete this transcript from Safari?'))return;await writes.catch(()=>{});await deleteSession(id);show('history')};$('#detail').onclick=async event=>{const button=event.target.closest('[data-action]');if(!button)return;const phrase=s.segments.find(x=>x.id===button.dataset.phrase);if(!phrase)return;if(button.dataset.action==='edit'){const english=prompt('Correct English translation',phrase.english||'');if(english===null)return;phrase.english=english.trim().slice(0,2000);phrase.edited=!!phrase.english;phrase.error='';await persist(s);openDetail(id)}else{phrase.english='';phrase.error='';phrase.edited=false;await persist(s);enqueue(s.id,phrase.id);openDetail(id);toast('Translation queued for retry')}}}
async function backup(){const sessions=await getSessions();const blob=new Blob([JSON.stringify({format:'kyng-interpreter-free-v2',exportedAt:new Date().toISOString(),sessions,glossary:state.glossary},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`KYNG-Interpreter-Backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}
async function restore(event){const file=event.target.files[0];if(!file)return;try{const body=JSON.parse(await file.text());if(!['kyng-interpreter-free-v1','kyng-interpreter-free-v2'].includes(body.format)||!Array.isArray(body.sessions))throw Error('Not a KYNG Interpreter backup.');await importSessions(body.sessions);if(Array.isArray(body.glossary)){state.glossary=body.glossary.filter(t=>typeof t.zh==='string'&&typeof t.en==='string').slice(0,100);saveGlossary()}await recover();renderGlossary();toast(`Imported ${body.sessions.length} sessions`)}catch(e){toast('Import failed: '+e.message)}event.target.value=''}
function saveGlossary(){try{localStorage.setItem('kyng-glossary-v2',JSON.stringify(state.glossary))}catch(e){toast('Could not save glossary: '+e.message)}}
function renderGlossary(){$('#glossaryList').innerHTML=state.glossary.map((term,index)=>`<div class="term-row"><span>${escapeHTML(term.zh)} → ${escapeHTML(term.en)}</span><button type="button" data-remove="${index}" aria-label="Remove term">Remove</button></div>`).join('')||'<p>No custom terms yet.</p>'}
function addTerm(event){event.preventDefault();const zh=$('#glossaryZh').value.trim();const en=$('#glossaryEn').value.trim();if(!zh||!en||state.glossary.length>=100)return toast('Enter a term; maximum 100 custom terms.');state.glossary.push({zh,en});saveGlossary();renderGlossary();event.target.reset()}
function removeTerm(event){const button=event.target.closest('[data-remove]');if(!button)return;state.glossary.splice(Number(button.dataset.remove),1);saveGlossary();renderGlossary()}
try{const terms=JSON.parse(localStorage.getItem('kyng-glossary-v2')||'[]');if(Array.isArray(terms))state.glossary=terms.filter(t=>typeof t.zh==='string'&&typeof t.en==='string').slice(0,100)}catch{}
render();recover().catch(e=>toast('Could not recover saved translations: '+e.message));worker.postMessage({type:'load'});if('serviceWorker'in navigator)navigator.serviceWorker.register(import.meta.env.BASE_URL+'sw.js',{scope:import.meta.env.BASE_URL}).catch(()=>{});
